### ISSUE TITLE
Retrieve events from the meter

### ISSUE THREAD

**Issue by elhachhouchi** [OSGP/Protocol-Adapter-DLMS#19]
### See story osgp/platform#150 for details
```
```

### Story: retrieve events (from the meter)
```
As a grid operator
I want OSGP to retrieve events
So that I can monitor the meter, take adequate and/or provide the retrieved events 
to 3rd parties (who requested the events)
```

#### Tasks:
- [ ] Define acceptance criteria
- [ ] Implement scenarios handle retrieve events request message
- [ ] Implement acceptance tests
- [ ] Test

#### Scenario: Handle retrieve events request message
```
Given a retrieve events request message from the core
And the request message contains a device id <<<deviceid>>>
And the request message contains a single events query action
And the events query contains a period from <<<startdate>>> until <<<enddate>>>
And a device with device id <<<deviceid>>> exists
And the device is online
When the request message is received
Then a connection with the device should be established
And the return message contains a correlation id <<<correlationid>>>
```

#### There are different event logs, the following OBIS codes are used in the capture_objects attribute of the event log: 
```
0-0:96.11.0.255 Standard event Log 
0-0:96.11.1.255 Fraud detection Log 
0-0:96.11.3.255 M-Bus event log 
0-0:96-11.4.255 Communication Session event log

Please the DLMS object in DLMS and DSMR documents
```
#### Input:
```
DeviceIdentification of the E meter (required)
Begin period (type: datetime) (required)
End period (type: datetime) (required)
Event type (Standard, Fraud, Mbus or Communication), if Event type is NULL, return all type events

```
 
#### Response:
```
Events (code + description)
```
